name: .NET Build

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04
    name: Build
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/cache@v2
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Setup DotNet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: Restore dependencies
        run: |
          dotnet restore

      - name: DotNet Build
        run: |
          dotnet build --no-restore
          dotnet build --configuration Release --no-restore
          dotnet pack --configuration Release --no-restore --no-build

      - name: DotNet Test
        run: |
          dotnet test --no-build --no-restore

      - name: Test
        run: dotnet test -c Release --collect:"XPLat Code Coverage" --settings coverlet.runsettings --results-directory "coverage" --verbosity normal --no-build --no-restore

      - name: Upload coverage reports
        if: ${{ always() }}
        uses: codecov/codecov-action@v1
        with:
          directory: ./coverage
          name: codecov-specshell
          fail_ci_if_error: true
          verbose: false
